name: test
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 21 * * *'
    
jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
               
    - name: Prepare
      run: |
        pip install pycryptodome
        sudo apt update
        sudo apt install -y -qq aria2
        python C.py --public ${{ secrets.PUBLIC }} --private ${{ secrets.PRIVATE }} --mode jiemi
        
    - name: Run
      run: |
        python aria.py -uid ${{ secrets.UID }} -c ${{ secrets.COOKIE }} --tag save
        cd image
        aria2c -c --input-file=urllist.txt
        
    
    - name: Upload
      run: |
        cd Upload
        python main.py

    - name: Clean
      run: |
        rm -rf image
        python C.py --public ${{ secrets.PUBLIC }} --private ${{ secrets.PRIVATE }} --mode jiami
                        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        BRANCH: main
        FOLDER: .
        BASE_BRANCH: main
                
                
                
