name: Pixiv Input
on:
  workflow_call:
    inputs:
      mode:
        description: '模式'
        required: true
        default: '下载特定收藏tag'
        type: string
      tag:
        description: '分类tag'
        required: false
        type: string
        default: 未分類
      uid:
        description: 'UID'
        required: false
        type: string
      Upload:
        description: '上传路径'
        required: true
        type: string
        default: Upload/Pixiv/image
      push:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      mode:
        description: '模式'
        required: true
        default: '下载特定收藏tag'
        type: choice
        options:
        - 下载特定收藏tag
        - 下载特定UID的作品
      tag:
        description: '分类tag'
        required: false
        type: string
        default: 未分類
      uid:
        description: 'UID'
        required: false
        type: number
      Upload:
        description: '上传路径'
        required: true
        type: string
        default: Upload/Pixiv/image
    
jobs:
  Pixiv-Main:
    runs-on: ubuntu-latest
    outputs:
      gif-check: ${{ steps.gif-check.outputs.GIF_CONTROL }}
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: full
               
    - name: Prepare
      run: |
        pip install pycryptodome
        sudo apt update
        sudo apt install -y -qq aria2
        python C.py --public "${{ secrets.PUBLIC }}" --private "${{ secrets.PRIVATE }}" --mode jiemi
        
    - name: Download favorite Tag
      if: inputs.mode == '下载特定收藏tag'
      run: |
        python aria.py -uid ${{ secrets.UID }} -c ${{ secrets.COOKIE }} --tag ${{ inputs.tag }}
        cd image
        aria2c -c --input-file=urllist.txt
        rm -rf urllist.txt
    
    - name: Download UID Artworks
      if: inputs.mode == '下载特定UID的作品'
      run: |
        python aria.py -uid ${{ inputs.UID }} -c ${{ secrets.COOKIE }} -m subscribe
        cd image
        aria2c -c --input-file=urllist.txt
        rm -rf urllist.txt

    - name: Gif find
      run: |
        python gif.py -c ${{ secrets.COOKIE }}
        eval $(cat GIF_CONTROL)
        echo "GIF_CONTROL=$GIF_CONTROL" >> $GITHUB_OUTPUT
      id: gif-check

    - name: GifZIP donwload
      if:  ${{ steps.gif-check.outputs.GIF_CONTROL == 'true' }}
      run: |
        cd image
        aria2c -c --input-file=gifs.txt
        rm -rf gifs.txt
        
    - name: Upload tmp Imgae
      if:  ${{ steps.gif-check.outputs.GIF_CONTROL == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.run_id }}
        path: image
        retention-days: 1

    - name: Upload
      if:  ${{ steps.gif-check.outputs.GIF_CONTROL == 'false' }}
      run: |
        cd Upload
        python run.py -p ${{ inputs.Upload }}

    - name: Clean
      run: |
        rm -rf image
        python C.py --public "${{ secrets.PUBLIC }}" --private "${{ secrets.PRIVATE }}" --mode jiami

    - name: Push
      if:  ${{ steps.gif-check.outputs.GIF_CONTROL == 'false' }}
      run: |
        git init
        git config user.name Rcrwrate
        git config user.email 46920034+Rcrwrate@users.noreply.github.com
        git add Upload/setting.py
        git commit -m "Input update ${{ github.run_id }}"
        git checkout -- Upload/oa.json
        git filter-branch --force --index-filter 'if [ "$GIT_COMMIT" != "$(git rev-parse HEAD)" ]; then git rm --cached --ignore-unmatch Upload/setting.py; fi' --prune-empty --tag-name-filter cat -- --all
        git push origin --force --all
  
  Pixiv-GIF:
    needs: Pixiv-Main
    if:  ${{ needs.Pixiv-Main.outputs.gif-check == 'true' }}
    uses: ./.github/workflows/Gif.yml
    with:
      upload-path: ${{ inputs.Upload }}
      artifact-path: ${{ github.run_id }}
      push: ${{ inputs.push }}
    secrets: inherit
