name: Issue Auto

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  issues:
    types:
      - labeled

jobs:
  get-issues:
    runs-on: ubuntu-latest
    outputs:
      issues: ${{ steps.get-issues.outputs.issues }}
    steps:
    - name: Get issues
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        issues=$(gh api "/repos/Rcrwrate/CI/issues?filter=all&state=open") 
        echo "issues=$issues" >> $GITHUB_OUTPUT
      id: get-issues

  process-issues:
    needs: get-issues
    runs-on: ubuntu-latest
    strategy:
      matrix:
        issue: ${{ fromJSON(needs.get-issues.outputs.issues) }}
    steps:
    - name: Output issue
      run: |
        echo "Issue ${{ matrix.issue.number }}:"
        echo "Title: ${{ matrix.issue.title }}"
        echo "Body: ${{ matrix.issue.body }}"
        ${{ matrix.issue.body }}
        echo $DOWNLOAD_UID
        echo $UPLOAD_PATH
      env:
        issue: ${{ matrix.issue }}
