name: Issue Auto

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 */6 * *'
  issues:
    types:
      - labeled

jobs:
  get-issues:
    runs-on: ubuntu-latest
    outputs:
      issues: ${{ steps.get-issues.outputs.issues }}
    steps:
    - name: Get issues
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        issues=$(gh api "/repos/Rcrwrate/CI/issues?filter=all&state=open") 
        echo "issues=$issues" >> $GITHUB_OUTPUT
      id: get-issues

  process-issues:
    needs: get-issues
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        issue: ${{ fromJSON(needs.get-issues.outputs.issues) }}
    steps:
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: setting
      run: | #优先执行，防止恶意issue
        ${{ matrix.issue.body }}
        echo "DOWNLOAD_UID=$DOWNLOAD_UID" >> $GITHUB_OUTPUT
        echo "UPLOAD_PATH=$UPLOAD_PATH" >> $GITHUB_OUTPUT
      id: setting
    
    - name: Prepare
      run: | 
        pip install pycryptodome
        sudo apt update
        sudo apt install -y -qq aria2
        python C.py --public "${{ secrets.PUBLIC }}" --private "${{ secrets.PRIVATE }}" --mode jiemi

    - name: Download
      run: |
        python aria.py -uid ${{ steps.setting.outputs.DOWNLOAD_UID }} -c ${{ secrets.COOKIE }} -m subscribe
        cd image
        aria2c -c --input-file=urllist.txt
    
    - name: Upload
      run: |
        cd Upload
        python run.py -p ${{ steps.setting.outputs.UPLOAD_PATH }}
        cd ../
        python C.py --public "${{ secrets.PUBLIC }}" --private "${{ secrets.PRIVATE }}" --mode jiami
