name: Issue Auto

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  issues:
    types:
      - labeled

jobs:
  get-issues:
    runs-on: ubuntu-latest
    outputs:
      issues: ${{ steps.get-issues.outputs.issues }}
    steps:
    - name: Get issues
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        issues=$(gh api "/repos/Rcrwrate/CI/issues?filter=all&state=open") 
        echo "issues=$issues" >> $GITHUB_OUTPUT
      id: get-issues

  process-issues:
    needs: get-issues
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        issue: ${{ fromJSON(needs.get-issues.outputs.issues) }}
    steps:
    - name: Output issue
      run: |
        ${{ matrix.issue.body }}
        python aria.py -uid $DOWNLOAD_UID -c ${{ secrets.COOKIE }} -m subscribe
        cd image
        aria2c -c --input-file=urllist.txt
        cd ../Upload
        pip install pycryptodome
        python C.py --public "${{ secrets.PUBLIC }}" --private "${{ secrets.PRIVATE }}" --mode jiemi
        python run.py -p $UPLOAD_PATH
        python C.py --public "${{ secrets.PUBLIC }}" --private "${{ secrets.PRIVATE }}" --mode jiami
