name: OA
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 22 * * *'
    
jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: OA
      run: |
        python C.py --public ${{ secrets.PUBLIC }} --private ${{ secrets.PRIVATE }} --mode jiemi
    
    - name: Upload
      run: |
        cd Upload
        python oa.py

    - name: Clean
      run: |
        python C.py --public ${{ secrets.PUBLIC }} --private ${{ secrets.PRIVATE }} --mode jiami
    
    - uses: shaowenchen/debugger-action@v2
      name: debugger
      timeout-minutes: 30
      continue-on-error: true
      with:
        ngrok_token: ${{ secrets.NGROK_TOKEN }} 
                        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        BRANCH: main
        FOLDER: .
        BASE_BRANCH: main
                
                
                
