name: OA
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 22 * * *'
    
jobs:
  OA:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: OA
      run: |
        pip install pycryptodome
        python C.py --public ${{ secrets.PUBLIC }} --private ${{ secrets.PRIVATE }} --mode jiemi
    
    - name: Upload
      run: |
        cd Upload
        python oa.py

    - name: Clean
      run: |
        python C.py --public ${{ secrets.PUBLIC }} --private ${{ secrets.PRIVATE }} --mode jiami


  Push:
    runs-on: ubuntu-latest
    needs: OA
    steps:                     
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        BRANCH: main
        FOLDER: .
        BASE_BRANCH: main
                
                
                
